== Wireless Intrusion Detection/Prevention Systems Protection Profile Module

https://commoncriteria.github.io/wids[image:https://github.com/commoncriteria/wids/actions/workflows/quick_build.yml/badge.svg[QuickBuild]]

This repository hosts the draft version of the Network Devices PP-Module
for Wireless Intrusion Detection/Prevention Systems (WIDS/WIPS) based on
the https://commoncriteria.github.io/pp/wids/wids-esr.html[Essential
Security Requirements (ESR)] for this technology class of products. This
repository is used to facilitate collaboration and development on the
draft document. See the link:#Release-Version[release] section if you
are looking for the officially released version for evaluations. A list
of products that have passed evaluation against this Protection Profile
can be found https://www.niap-ccevs.org/Profile/Info.cfm?id=395[here].

=== Draft Version

* https://commoncriteria.github.io/pp/wids/wids-release.html[Wireless
Intrusion Detection/Prevention Systems (WIDS/WIPS) Protection Profile
Module (PP-Module)] (html)
* https://commoncriteria.github.io/pp/wids/wids-release-paged.pdf[Wireless
Intrusion Detection/Prevention Systems (WIDS/WIPS) Protection Profile
Module (PP-Module)] (pdf)

=== Release Version

* https://www.niap-ccevs.org/Profile/Info.cfm?id=395[Wireless Intrusion
Detection/Prevention Systems (WIDS/WIPS) Extended Package (EP) v1.0]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community.

* https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/wids/issues[repository issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/wids.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
